### ISSUE TITLE
can't find it in hacs

### ISSUE THREAD

**Issue by malfurion** [fwmarcel/home-assistant-divera#10]
The Divera Repo can't be found in hacs actually

![image](https://user-images.githubusercontent.com/634939/212935092-9291b820-1de1-4e69-91eb-e7521ddc68b7.png)

also the button in the readme doesn't work an directs to a 404 error page

![image](https://user-images.githubusercontent.com/634939/212935245-94f79464-f230-492e-8f44-2febca5b1e17.png)

**Comment by fwmarcel** [comment]
Hello @malfurion,
have u added this repository to your custom repositories?
If not here is a guide:  https://hacs.xyz/docs/faq/custom_repositories/

**Comment by malfurion** [comment]
Ah thanks that was what i missed sorry :D
