### ISSUE TITLE
[Bug]: Can't setup integration after update to 1.0.1

### ISSUE THREAD

**Issue by N1c093** [fwmarcel/home-assistant-divera#106]
### Requirements

- [X] I have updated Divera Integration to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

I just updated from 0.07 to version 1.0.1. Now the integration doesn't start successfully. I get the following error in the log:

```
2024-03-27 20:03:07.423 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry (my Name) for divera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/divera/__init__.py", line 50, in async_setup_entry
    cluster_name: str = clusters[str(ucr_id)]
                        ~~~~~~~~^^^^^^^^^^^^^
KeyError: '(my ID)'
```

I already tried to delete my configuration and restarted the setup flow, sadly the issue still exists.

Was I too quick with the update and you are already aware of this bug?

### Context

YAML state
```yaml

```

### Environment

```markdown
- HA Version: 2024.3.3
- Divera Version: 1.0.1
```

**Comment by fwmarcel** [comment]
Thank you for your feedback @N1c093 
An automatic upgrade from versions 0.0.7 or 0.0.8 to release 1.0.0 caused this error.

With version 1.0.1 this should actually be fixed. 
I'll try to recreate the situation again...

Have you already restarted Home Assistant as the "Repair" suggests?

**Comment by N1c093** [comment]
Yes, I deleted my configuration (see screenshot), rebooted HA and tried to configure the integration again. 
![image](https://github.com/fwmarcel/home-assistant-divera/assets/59510296/a492384f-2c2c-4079-9260-0d55a7593716)

So it should be like a fresh installation and the old version 0.0.7 shouldn't be a problem.

**Comment by fwmarcel** [comment]
I have now been able to reproduce the error.

For me, it occurs once after the update.
Once the error has occurred. It no longer appears after another reboot. 

I am currently still looking for the cause. I suspect a timing problem.

If I remove the integration and add it again, it works without any problems.

**Comment by N1c093** [comment]
I gave it another try.

1. Setup the integration and get the error described above.
2. Don't remove the configuration
3. RestartHome Assistant
4. Integration is working

 So after the error occurred, I had to restart Home Assistant.

Before I tried to removed the configuration and did a restart afterwards.

**Comment by N1c093** [comment]
I think you are doing a great job👍
