### ISSUE TITLE
Prüfintervall

### ISSUE THREAD

**Issue by EasySIX4491** [fwmarcel/home-assistant-divera#11]
Hi, ist es möglich den Intervall wo der die Alarme testet zu verringern? 
Glaube derzeit liegt der bei  60 sec. 
Da ich aber damit auch die Beleuchtung steuern möchte im Einsatzfall sind 60 sec sehr lang wenn der nicht zufällig kurz nach Alarm prüft.

Mfg 
EasySIX

**Comment by fwmarcel** [comment]
Hallo @EasySIX4491 

60 Sekunden können im Einsatzfall durchaus lang erscheinen, da gebe ich dir auf jeden Fall recht.
Was für ein Intervall schwebt dir denn vor?
Grundsätzlich kann ich mal schauen, dass ich eine Konfigurationsoption einbauen kann.
Sodass der Wert reduziert werden kann.

Allerdings habe ich keine Kenntnis darüber, wie Divera und deren API mit "vielen" Anfragen umgeht.
Ich kann mir vorstellen, dass es dort gewisse Einschränkungen gibt.
Aus diesem Grund ist das Intervall im Moment vorsichtig gewählt.

**Comment by EasySIX4491** [comment]
Na ja,  derzeit stellt der ja die Anfragen soweit ich das verstanden habe an den Server von Divera - geht es nicht umgekehrt auch? Quasi wie bei der App von Divera das eine PUSH-Nachricht an dein Programm gesendet wird anstatt andersrum anzufragen ob etwas anliegt?

**Comment by hendrik1120** [comment]
@EasySIX4491 https://help.divera247.com/pages/viewpage.action?pageId=44172211
Sogar mit Video Anleitung.

**Comment by fwmarcel** [comment]
Hallo @EasySIX4491 
Da Webhooks nur von dem Administrator einer Einheit eingerichtet werden können und im normalen Nutzerinterface nicht zur Verfügung stehen, ist ein Push-Mechanismus ist für diese Integration nicht möglich und vorgesehen.

Möchte man ein Push-Mechanismus haben, kann ein Webhook natürlich auch ohne diese Integration eingerichtet werden. Siehe Link von @hendrik1120  und https://www.home-assistant.io/docs/automation/trigger/#webhook-trigger

**Comment by N1c093** [comment]
Ich mische mich mal mit ins Gespräch ein.

So wie ich es verstehe, gibt es bei den "offiziellen" Home Assistant Integrationen wohl die Empfehlung/Vorgabe, dass der Benutzer den Poll-Interval nicht mehr anpassen kann. 
Siehe: 
https://github.com/home-assistant/core/pull/68386#discussion_r830668959
https://github.com/home-assistant/core/issues/69477#issuecomment-1091253823

Natürlich ist man in einer "custom component" nicht an die Vorgabe gebunden.

Die Lösung für das Problem ist über eine Automatisierung alle X Sekunden den Dienst `homeassistant.update_entity` aufzurufen.
https://www.home-assistant.io/integrations/homeassistant/#service-homeassistantupdate_entity

**Comment by fwmarcel** [comment]
@N1c093 Danke für den Hinweis bezüglich der Anpassung des Poll-Intervalls durch Nutzer.
Dem werde ich mich gerne auch in dieser custom Integration nach richten.

Eine Lösung auf eigene "Gefahr" ist eben den Dienst eben selber aufzurufen.
Damit würde ich dieses Thema hier beenden.
