### ISSUE TITLE
Alarm schon bei closed = true nicht mehr anzeigen

### ISSUE THREAD

**Issue by dabenzel** [fwmarcel/home-assistant-divera#12]
Moin!
Ich habe bei mir das "Problem", dass bei mir ein geschlossener Alarm noch weiterhin angezeigt wird. In der Divera App ist der beendet.
Siehe:
![image](https://user-images.githubusercontent.com/2480235/216837697-2248ee9b-5f35-4c7a-8025-4ba29d7c60d6.png)

Der Sensor ist jedoch weiterhin aktiv.
Könnte man eine Option einbauen, dass ein geschlossener Alarm den Sensor schon wieder auf "nicht verfügbar" stellt?

---
Erklärung:
Wir können die Alarme in Divera frühestens nach 24h Archivieren (das würde den Sensor ja wieder ändern), da die LST bei jeder Aktualisierung des Alarms (Status, Nachalarmierung, etc) den Divera-Alarm aktualisiert.
Wenn wir den Alarm vorzeitig archivieren würden, würde eine neualarmierung stattfinden, was nicht gewollt ist.

**Comment by fwmarcel** [comment]
Moin,

ich verstehe das "Problem".
Allerdings zeigt der Sensor solange einen Alarm an, solange dieser auch in der App dargestellt wird. Also solange dieser nicht archiviert ist. Das Verhalten ist dementsprechend so gewollt.

Die einfachste Möglichkeit wäre glaube ich das ganze mit einem Template (Sensor) zu lösen. Je nachdem an welcher Stelle (Dashboard oder Skript) das verhalten gewünscht ist.

```
{% if state_attr('sensor.divera_alarm','closed') -%}
Nicht Verfügbar!
{%- else -%}
{{ states('sensor.divera_alarm') }}
{%- endif %}
```

**Comment by dabenzel** [comment]
Moin!
Ja, passt für mich. Hab schon die Markdown-Kachel angepasst, dass ich nicht irgendwann zu verwirrt bin:

```
{% if states('sensor.divera_alarm')=='unknown'%}
\- Kein Alarm -
{%else%}
{% if state_attr('sensor.divera_alarm','closed')%}
# --GESCHLOSSEN--
{%else%}{% endif %}
# {{ states('sensor.divera_alarm') }}
---
__Text:__ {{ state_attr('sensor.divera_alarm','text') }}
__Adresse:__ {{ state_attr('sensor.divera_alarm','address') }}
__Zeit:__ {{ state_attr('sensor.divera_alarm','date') }}
{% set groups = state_attr('sensor.divera_alarm','groups') %}
{% for g in groups %}
  - {{ g }}
{%- endfor %}
{% endif %}
```

Ich teste das mal mit einem Template-Sensor!

**Comment by dabenzel** [comment]
Fallls jemand das Template übernehmen will (annahme: Der Quell-Sensor heißt `sensor.divera_alarm`)

```configuration.yaml
  - platform: template
    sensors:
      divera_real_alarm:
        unique_id: "divera_real_alarm"
        value_template: >-
          {% if state_attr('sensor.divera_alarm','closed') -%}
          unknown
          {%- else -%}
          {{ states('sensor.divera_alarm') }}
          {%- endif %}
        icon_template: mdi:alarm-light
        attribute_templates:
          date: "{{ state_attr('sensor.divera_alarm','date') }}"
          address: "{{ state_attr('sensor.divera_alarm','address') }}"
          latitude: "{{ state_attr('sensor.divera_alarm','latitude') }}"
          longitude: "{{ state_attr('sensor.divera_alarm','longitude') }}"
          text: "{{ state_attr('sensor.divera_alarm','text') }}"
```
