### ISSUE TITLE
[Bug]: Alarm Answer "Not answered"

### ISSUE THREAD

**Issue by JbbDE** [fwmarcel/home-assistant-divera#135]
### Requirements

- [X] I have updated Divera Integration to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Seit neustem zeigt die Integration nur noch "Not answered" beim Attribut "Answered" an, obwohl ich auf den letzten Alarm geantwortet habe.

### Context

YAML state
```yaml

```

### Environment

```markdown
- HA Version: 2024.5.2
- Divera: 1.1.1
```

**Comment by fwmarcel** [comment]
You are absolutely right. 
I have found the bug and it will be fixed with the next release.
