### ISSUE TITLE
[Feature]: Add Alarm-Number to Alarm-Sensor in HA

### ISSUE THREAD

**Issue by dabenzel** [fwmarcel/home-assistant-divera#141]
### Requirements

- [X] I have updated Divera Integration to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

-

### Describe the solution you'd like

When having placed an automation on the Alarm-Sensor in HomeAssistant and the Keyword changes/increases (FEU -> FEU 2 -> ...) the automation always fires because the alarm gets updated in Divera. 
When the trigger is something stable like the Divera Alarm-Number, you can avoid the automation always firing

**Comment by dabenzel** [comment]
Hey, if it's okay for you, I'd like to implement this myself first (want to learn Python and custom HA-Integrations)

**Comment by N1c093** [comment]
@dabenzel The alarm sensor already have an attribute `id` which is an unique alarm id.
Or do you mean something else?

The blueprint still have to be updated. I already have this prepared and will create a pull request.

**Comment by N1c093** [comment]
Yes, see screenshot:
![image](https://github.com/fwmarcel/home-assistant-divera/assets/59510296/64dafde3-d68d-4222-a4a3-5509fd6bc4f7)

**Comment by dabenzel** [comment]
So it's this Divera-Field?
![image](https://github.com/fwmarcel/home-assistant-divera/assets/2480235/efafdbe9-7e11-461a-b29e-6b02ad891a4d)

**Comment by fwmarcel** [comment]
The ID and the Alarm number are in fact two different things. 

The Alarm number itself is not yet available. 
This still needs to be added. 
If you explicitly need the content of the ID.

If you just want to avoid triggering the automation again, you can fall back on the ID.

**Comment by fwmarcel** [comment]
Of course you are welcome to implement this yourself. 
I also use the project for myself to learn Python and Home Assistant

**Comment by fwmarcel** [comment]
The change is now available in the newsest release
