### ISSUE TITLE
[Bug]: Sensor wird in Karte angezeigt

### ISSUE THREAD

**Issue by Ruud2702** [fwmarcel/home-assistant-divera#190]
### Requirements

- [X] I have updated Divera Integration to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Der Sensor wird in der Karte im Atlantik angezeigt. Vermutlich aufgrund der Sensordaten Latitude
0 und Longitude 0.

### Expected Behavior

Es wäre schön wenn man den Sensor von der Karte ausblenden könnte.

### Context

YAML state
```yaml

```

### Environment

```markdown
- HA Version: 2024.8.1
- Mushroom:
```

**Comment by N1c093** [comment]
Ich vermute, dass eure Leitstelle kein GPS Koordinaten an Divera übergibt und somit der Standard "Latitude 0 und Longitude 0" verwendet wird.

Seit dem HA-Release 2024.4 kannst du die Map in Home Assistant selbst anpassen und auswählen welche Entitäten auf der Karte angezeigt werden. So könntest du Divera eigenständig aus der Karte ausblenden.
https://www.home-assistant.io/blog/2024/04/03/release-20244/#map-dashboard

**Comment by fwmarcel** [comment]
@N1c093 hat an der Stelle recht. Werden bei dir die Alarme über die API gespießt, bietet die Divera Reverse Geocoding an. 
Ansonsten ist das hier kein Fehler dieser Integration.
