### ISSUE TITLE
Warning - "device_state_attributes" deprecated

### ISSUE THREAD

**Issue by N1c093** [fwmarcel/home-assistant-divera#2]
Hello,

in my log I get the following warning:

`2022-03-02 10:55:40 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.divera_state (<class 'custom_components.divera.sensor.DiveraSensor'>) implements device_state_attributes. Please report it to the custom component author.`

Thank you.
Nico

**Comment by fwmarcel** [comment]
Hello,

thanks for reporting and give a solution.
