### ISSUE TITLE
[Feature]: Extend the automation Template for Groups in Alarm

### ISSUE THREAD

**Issue by dabenzel** [fwmarcel/home-assistant-divera#20]
### Requirements

- [X] I have updated Divera Integration to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

I am an Admin of our Brigade in Divera. There are different Groups which are alarmed for different RICs.
My User is in one of these groups. Because I am an Admin, I can see the Alarm in the App (but I dont get a notification).

Problem: Also in Divera the Sensor is in "Alarm"-State and my automation runs. Even if the alarmed Group is not one of which I am member of.

### Describe the solution you'd like

Extend the Automation Template so it is possible to also filter on Groups (Maybeo not really good, because the Name can change)

### Describe alternatives you've considered

Enrich the Automation with Group-Checks

### Additional context

Maybe not easy since HomeAssistant doesn't know the Groups I am part of. So a DropDown isn't possible, only String-Matching

**Comment by fwmarcel** [comment]
Hello 
I already know the situation. Because I also see all alarms in my unit.
For this reason, the sensor has the attribute "self_addressed", which I already used.
I will add the changes for blueprint. Should be relatively fast...
