### ISSUE TITLE
[Bug]: Different Alarm, same title -> No automation triggered

### ISSUE THREAD

**Issue by JbbDE** [fwmarcel/home-assistant-divera#210]
### Requirements

- [X] I have updated Divera Integration to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

First Alarm fired title "F2" (Feuer 2), the automation is triggered. 7 Days later, a alarm, also an "F2" is called, even description changes, date changes, but the automation isn't triggered.

### Expected Behavior

Automation should be triggered with every new alarm, even with the same title

### Context

YAML state
```yaml

```

### Environment

```markdown
- HA Version: 2024.11
- Divera Version: 1.2.1
- Blueprint Version: Unknown
```

**Comment by fwmarcel** [comment]
the behavior is correct. Ideally, the automation should always be triggered when the ID of the alarm changes. I think that should work...

**Comment by fwmarcel** [comment]
I've had a look. the blueprint is currently designed to only trigger when the alarm ids change. Is your alarm combined? And are you using the current blueprint version?

**Comment by JbbDE** [comment]
When was the last change?

**Comment by fwmarcel** [comment]
@N1c093 modified the blueprint 6 months ago...
You can take control of your automation / blueprint as follows:
https://www.home-assistant.io/docs/automation/using_blueprints/
Have a look if the trigger attribute is set.

**Comment by JbbDE** [comment]
okay, that was the problem xD
