### ISSUE TITLE
Dir not find the Integration 

### ISSUE THREAD

**Issue by tobias161183** [fwmarcel/home-assistant-divera#31]
### Requirements

- [X] I have updated Divera Integration to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Hi,

I now have opened a new issue.
HA ist complete new for me.

Cloud you please tell me how to geht the Integration?

Thanks ans best regards
Tobi

### Context

YAML state
```yaml

```

### Environment

```markdown
- HA Version:
- Mushroom:
```

**Comment by fwmarcel** [comment]
please follow the instructions below
https://hacs.xyz/docs/faq/custom_repositories/

and use the following url in the dialog
https://github.com/fwmarcel/home-assistant-divera

**Comment by tobias161183** [comment]
Thanks, now it is working.

But I tried to import the blueprint: https://github.com/fwmarcel/home-assistant-divera/blob/main/divera-blueprint.yaml via Einstellungen - Blaupausen, but got a fault message.
![image](https://github.com/fwmarcel/home-assistant-divera/assets/139229074/6b071032-c68a-4a54-bdc8-042ed1b3c0a5)

**Comment by fwmarcel** [comment]
The error is tracked in #36
