### ISSUE TITLE
[Bug]: Blueprint has an error

### ISSUE THREAD

**Issue by samgeorge** [fwmarcel/home-assistant-divera#36]
### Requirements

- [X] I have updated Divera Integration to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

When installing the blueprint it returns an unknown error

### Context

YAML state
```yaml

```

### Environment

```markdown
- HA Version:
- Mushroom:
```

**Comment by djens69** [comment]
Hi, I installed the Integration today and i have the same error.

**Comment by snarman** [comment]
Hello,

using the commit from 03 Jul 2022 "9cd8c47" let's me import the blueprint without error.
https://github.com/fwmarcel/home-assistant-divera/blob/9cd8c47e4281b6993f239c786bb627c0baa6d219/divera-blueprint.yaml

**Comment by N1c093** [comment]
Could you check, if the newest blueprint is working now? My Pull Request with the bugfix was merged.

**Comment by snarman** [comment]
> Could you check, if the newest blueprint is working now? My Pull Request with the bugfix was merged.

Import is working now. Cool, thanks a lot.
