### ISSUE TITLE
[Feature]: Response to alarm Attribute / Sensor

### ISSUE THREAD

**Issue by JbbDE** [fwmarcel/home-assistant-divera#68]
### Requirements

- [X] I have updated Divera Integration to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

I use this integration to start automations that trigger light or notifications, when I get a new alarm. But sometimes I can't leave home, so I respond with "Nicht einsatzbereit" to the alarm. Then all automations still go on, because there is no attribute / sensor to use my response as an condition to stop it.

### Describe the solution you'd like

I don't know if the Divera API features something like this, but it would be great to have the response to the alarm as an attribute to the alarm sensor.

**Comment by fwmarcel** [comment]
I have a similar scenario at home myself.
I check the status, which I set via my smartphone if necessary.

Home Assistant also allows actions to be canceled under certain conditions.
In your case, this would look like this:

```
if:
  - condition: state
    entity_id: select.divera_user_status
    state: nicht einsatzbereit
then:
  - stop: ""
```

Or you can reverse the condition so that you only perform the action when you arrive.

Hope that might be enough for you.

**Comment by JbbDE** [comment]
I know that I can do this, but if I only answer this alarm to be not available, but I am still available in the user status, how can I stop the automation otherwise?

**Comment by fwmarcel** [comment]
Then I am not sure if I have understood the problem. 

The feedback for the alarms are also status changes. And therefore the same as the normal status changes. 

The whole thing behaves in the same way for me.  If this is not the case for you, I need more information on exactly what this looks like.

**Comment by JbbDE** [comment]
I am no Divera Administrator for our fire department, but I think it can be configured, so that if your status isn't "nicht einsatzbereit ohne Alarm", you can receive alarms and respond with e.g. "5mins" without changing your overall status(?)
this [Page](https://help.divera247.com/pages/viewpage.action?pageId=19563265) might explain my interpretation

**Comment by fwmarcel** [comment]
Okay. Yes, the description helps me.
Apparently the feedback is configured differently in your unit than in mine. 

You are only interested in your own feedback on the deployment, correct?
Not setting the response via Home Assistant.

I've had a rough look at it. I think I can add this information as an attribute to the sensor.

I just need to see when I can get this implemented.

**Comment by JbbDE** [comment]
that would be great, yes

**Comment by fwmarcel** [comment]
@JbbDE Please install the new version 0.0.8.
Your desired feature is included. Please test it for yourself and give me feedback.

**Comment by JbbDE** [comment]
![Screenshot_2024-01-09-10-02-26-45_c3a231c25ed346e59462e84656a70e50](https://github.com/fwmarcel/home-assistant-divera/assets/70019640/5f25fae7-c3b8-4b58-bbf0-47c4b001ffd8)
Seems to work, I will wait for the next one😅

**Comment by JbbDE** [comment]
Works fine, thank you!
