### ISSUE TITLE
[Bug]: Untereinheiten werden nicht erkannt.

### ISSUE THREAD

**Issue by DuncanMacLoud** [fwmarcel/home-assistant-divera#69]
### Requirements

- [X] I have updated Divera Integration to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Wenn man in mehreren Untereinheiten ist wir immer nur die Haupteinheit (Masteraccount) ausgelesen.

### Expected Behavior

Es müssten mehrere Untereinheiten mit der selben ID abgefragt werden können.

### Context

YAML state
```yaml

```

### Environment

```markdown
- HA Version:
- Mushroom:
```

### Anything else?

Moin, 
ich arbeite in einer Leitstelle. Mein Kollege hat mit Divera gesprochen und es gibt eine undokumentierte API Abfrage dafür.
Er hat das für i.O. Broker implementiert.
Wenn Interesse besteht bitte melden dann würde mein Kollege Dir gerne Zeigen was gemacht werden muss.
kontakt@buettner-arlt.de

**Comment by fwmarcel** [comment]
Mir ist bekannt, dass mehrere Einheiten (bsp. in Form von einer Doppelmitgliedschaft) aktuell noch nicht von dieser Integration unterstützt werden.
Aktuell wird immer die Stammeinheit geladen. So ist es auch aus der Dokumentation von Divera zu lesen.
Ist dies mit Haupteinheit und Untereinheit gemeint? Oder sprechen wir hier von der Divera Pro Version, welche mehrere Einheiten erlaubt?

Informationen zur Abfrage helfen natürlich bei der Entwicklung.

**Comment by fwmarcel** [comment]
Okay. Ich nehme das mal mit in die Entwicklung auf. Im Gegensatz zu den anderen Weiterentwicklungen, schätze ich den Aufwand hier etwas größer ein. Ich muss mal schauen, wann ich dazu komme.

**Comment by M-Wiemann** [comment]
@DuncanMacLoud weißt du wo die NutzerId (ucr) steht, bzw wie man diese für die jeweiligen Einheiten heraus bekommt?

**Comment by fwmarcel** [comment]
@M-Wiemann Das ist korrekt. Die API bzw. Url wird aktuell auch verwendet. Ich plane aktuell die Einheit(en) beim hinzufügen der Integration auswählbar zu machen. Ich passe gerade die Dialoge darauf hin an.

**Comment by fwmarcel** [comment]
@M-Wiemann & @DuncanMacLoud 
Mit der neuen Pre-Release Version 1.0.0 sind nun mehrere Einheiten möglich. Diese kann gerne getestet werden.

**Comment by M-Wiemann** [comment]
Hab die Pre-Release installiert und sieht erst mal gut aus.
Ich warte dann mal auf den nächsten Alarm.
Vielen Dank für die Arbeit.

**Comment by fwmarcel** [comment]
Die Version ist jetzt released. Sollten noch Probleme auftauchen oder Features Fehlen gerne ne neuen Issue dafür aufmachen. Danke.
