### ISSUE TITLE
Frage 

### ISSUE THREAD

**Issue by Elemirus1996** [fwmarcel/home-assistant-divera#7]
Hallo Marcel, kurze frage wie kann man die restlichen Infos, die von einem Alarm übertragen werden, auslesen? Wenn ich den Sensor auf  das Dashboard lege sehe ich nur das Stichwort.
mit freundlichen Gruß 
Paul

**Comment by fwmarcel** [comment]
Hallo @Elemirus1996,

Einerseits kannst du das Attribut bei der Entity Card auswählen. D.h. du müsstest für jedes dazustellendes Attribut die Karte x mal hinzufügen und auswählen.

Andererseits gibt es die Markdown Card. In der du ja belieben Template Text hinzufügen kannst.
https://www.home-assistant.io/dashboards/markdown/
Diese verwende ich im Moment, jedenfalls bis ich die Zeit gefunden habe etwas hübscheres zu bauen.
Hier mal ein Beispiel:

```
# {{ states('sensor.divera_alarm') }}
---
{{ state_attr('sensor.divera_alarm','text') }}
{{ state_attr('sensor.divera_alarm','date') }}
{% set groups = state_attr('sensor.divera_alarm','groups') %}
{% for g in groups %}
  - {{ g }}
{%- endfor %}
```

Gerade bei der Darstellung gibt es natürlich noch x weitere Wege, welche natürlich auch hübscher und komplexer sind.
Mit freundlichen Grüßen

Marcel

**Comment by Elemirus1996** [comment]
Hm, leider kann ich bei der Entity Card kein Attribut auswählen.


fwmarcel ***@***.***> schrieb am So. 13. Nov. 2022 um 20:08:

**Comment by fwmarcel** [comment]
@Elemirus1996 da bin ich verwundert. Laut Dokumentation ist dies Möglich. Siehe https://www.home-assistant.io/dashboards/entity/

Bei mir klappt dies auch...
<img width="957" alt="Bildschirm­foto 2022-11-13 um 21 03 50" src="https://user-images.githubusercontent.com/22275913/201541944-819e24fe-1dd6-42dd-acdc-29a5d5a82894.png">

**Comment by Elemirus1996** [comment]
fwmarcel ***@***.***> schrieb am So. 13. Nov. 2022 um 21:04:

**Comment by Elemirus1996** [comment]
Ah hab das Problem bei mir in deckt, kann es irgendwie nur ändern wenn ein
Einsatz offen ist.

Paul Schulz ***@***.***> schrieb am So. 13. Nov. 2022 um
21:09:
