### ISSUE TITLE
Docker-Image für HA-Core

### ISSUE THREAD

**Issue by Przivl99** [fwmarcel/home-assistant-divera#71]
### Requirements

- [X] I have updated Divera Integration to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

Nicht vorhandener Addon store bei nutzung von homeassistant-core

### Describe the solution you'd like

Moin, gäbe es die möglichkeit ein das du deine intigration auch als Docker image/compose config anbietest?
Wäre für die die homeassistant-core nutzen bestimmt sehr praktisch.

liebe grüße.

**Comment by fwmarcel** [comment]
Die Integration kann über HACS installiert und auch in Home Assistant Core überall genutzt werden.  Dafür muss nichts extra angeboten werden.
