### ISSUE TITLE
Abort keyword is not optional in blueprint

### ISSUE THREAD

**Issue by PushAnyKey** [fwmarcel/home-assistant-divera#72]
### Requirements

- [X] I have updated Divera Integration to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

left "(optional) Abort keyword" blank

### Expected Behavior

no keyword necessary to save the blueprint

### Steps To Reproduce

download blueprint, configure without optional abord keyword, try to save, see error-message: "Message malformed: Missing input abort_keyword"

### Context

YAML state
```yaml

```

### Environment

```markdown
- HA Version:
- Mushroom:
```

**Comment by fwmarcel** [comment]
@PushAnyKey please try this new Version. Thanks @N1c093 for fixing this issue
