### ISSUE TITLE
Unable to change user satus in pre-releese 0.0.8

### ISSUE THREAD

**Issue by roschi02** [fwmarcel/home-assistant-divera#79]
### Requirements

- [X] I have updated Divera Integration to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

If I change the user status, I get the error: 
`Failed to call service select/select_option. 'DiveraData' object has no attribute 'get_state_if_from_name'`

### Expected Behavior

User status should change.

### Steps To Reproduce

Install version 0.0.8 and attempt to change the user status.

### Environment

```markdown
- Core: 2024.2.2
- Supervisor: 2024.01.1
- Operating System: 11.5
- Divera Version: 0.0.8
```

### Anything else?

Changing back to version 0.0.7 fixed the issue for me.

**Comment by fwmarcel** [comment]
Thanks for reporting. It looks like a missspellig. I will resolve this with the next Release.
